### ISSUE TITLE
minify svg with squoosh?

### ISSUE THREAD

**Issue by codemonkeynorth** [chiiya/laravel-mix-image-minimizer#4]
Hi is it possible to minify (clean, remove comments etc) SVGs with squoosh or will I have to switch to the imagemin version?

alternatively do you have a suggestion for working with svg's separately to squoosh?

thanks

update.. 
I was hoping to do something like this but it doesn't work... the svg's don't get minified

   ```javascript
    .images({
        // jpg, png etc
        implementation: 'squoosh',
        webp: true,
    },
    {
        // svg
        implementation: 'imagemin',
        options: {
            plugins: [
                [
                    "imagemin-svgo", 
                    {
                        plugins: ['preset-default']
                    }
                ]
            ]
        }
    })   
````

**Comment by chiiya** [comment]
For squoosh apparently [there is no support yet](https://github.com/GoogleChromeLabs/squoosh/issues/884). In your example you used an invalid configuration syntax combining squoosh and imagemin. 

Have you tried just using imagemin instead of squoosh entirely?

```js
mix.images({
  implementation: 'imagemin',
  webp: true,
});
```

**Comment by codemonkeynorth** [comment]
Hi, yes I ended up sticking with imagemin implementation as I couldn't get the normal laravel-mix-imagemin to work either (some issue with require & copy options)

This will do fine for now thanks
